
services:
  client-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: rag-chat-db-client-dev
    ports:
      - "3002:3000"
    volumes:
      - ./src:/app/src
      - ./app:/app/app
      - ./public:/app/public
      - ./next.config.ts:/app/next.config.ts
      - ./package.json:/app/package.json
      - /app/node_modules
    environment:
      - .env
    stdin_open: true
    tty: true
    networks:
      - ragchatdb-network
networks:
  ragchatdb-network:
    driver: bridge